name: Contanier Build - Compare GHA build vs Depot

on:
  pull_request:
    branches:
      - mealie-next

jobs:
  build-and-compare:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Override __init__.py
        run: |
          echo "__version__ = \"boc-the-git:mealie-depot\"" > ./mealie/__init__.py

      - uses: depot/setup-action@v1

      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          project: srzjb6mhzm
          file: ./docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: |
            boc-the-git:mealie-depot
          build-args: |
            COMMIT=${{ github.sha }}
            
      - name: Load and tag docker image
        run: |
          docker image ls

  # build-gha:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #   steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Override __init__.py
        run: |
          echo "__version__ = \"boc-the-git:mealie-gha\"" > ./mealie/__init__.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          # load: true
          tags: |
            boc-the-git:mealie-gha
          build-args: |
            COMMIT=${{ github.sha }}

  # compare-images:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Pull images for comparison
  #       run: |
  #         docker pull boc-the-git:mealie-gha
  #         docker pull boc-the-git:mealie-depot
            
      - name: Load and tag docker image
        run: |
          docker image ls
        
      - name: Run container-diff
        uses: GoogleContainerTools/container-diff/actions@0695621c48497a11a893a8fc0af7965c674123da
        with:
          command: diff          
          args: daemon://boc-the-git:mealie-gha daemon://boc-the-git:mealie-depot --type=file --output="./container-diff-file.txt"

      - name: Print container-diff
        run: |
          cat ./container-diff-file.txt
