name: Build Containers

on:
  workflow_call:
    # inputs:
    #   tag:
    #     required: true
    #     type: string
    # secrets:
    #   DOCKERHUB_USERNAME:
    #     required: true
    #   DOCKERHUB_TOKEN:
    #     required: true

# on:
#   push:
#     branches:
#       - 'actions-testing'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Override __init__.py
        run: |
          echo "__version__ = \"${{ github.sha }}\"" > ./mealie/__init__.py

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          # push: true
          tags: test/actions-test
          build-args: |
            COMMIT=${{ github.sha }}
