name: Test if the changes on branch feat-update-docs-on-new-release work!
on:
  release:
    types: [created]

jobs:
  update-image-tags:
    name: Update image tag in sample docker-compose files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Modify version strings
        run: |
          sed -i 's/:v[0-9]*.[0-9]*.[0-9]*/:${{ github.event.release.tag_name }}/' docs/docs/documentation/getting-started/installation/sqlite.md
          sed -i 's/:v[0-9]*.[0-9]*.[0-9]*/:${{ github.event.release.tag_name }}/' docs/docs/documentation/getting-started/installation/postgres.md

      - name: Commit updates
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            docs/docs/documentation/getting-started/installation/sqlite.md
            docs/docs/documentation/getting-started/installation/postgres.md
          commit-msg: "Change image tag, for release ${{ github.event.release.tag_name }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
